# Default values for c#.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/deliverymachine/lunchup-backend
  tag: 0.1.13
  pullPolicy: IfNotPresent

db:
  postgresqlUsername: &dbUser lunchup
  postgresqlPassword: &dbPassword lunchup
  postgresqlDatabase: &dbName lunchup

# define environment variables here as a map of key: value
env:
  Database__lunchUp__Username: *dbUser
  Database__lunchUp__Password: *dbPassword
  Database__lunchUp__Host: jx-db
  Database__lunchUp__Port: "5432"
  Database__lunchUp__Database: *dbName
  ASPNETCORE_ENVIRONMENT: production

# enable this flag to use knative serve to deploy the app
knativeDeploy: false

service:
  name: lunchup-backend
  type: ClusterIP
  externalPort: 5000
  internalPort: 80
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 1
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 256Mi
probePath: /
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  failureThreshold: 1
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
