version: '3'
services:
  db:
    image: postgres:12
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-test:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: lunchup
      POSTGRES_DB: lunchup
      POSTGRES_USER: lunchup
volumes:
  postgres-data:
  postgres-data-test: